export const DIRECTIONS = ["up", "right", "down", "left"];
export const PLAYER_SLOTS = ["p1", "p2"];
export const ROOM_PHASES = ["waiting", "ready", "countdown", "playing", "finished"];
export const ERROR_CODES = [
    "invalid_message",
    "unsupported_version",
    "invalid_session",
    "room_not_found",
    "room_full",
    "not_in_room",
    "already_in_room",
    "queue_full",
    "capacity_reached",
    "invalid_state",
    "rate_limited",
    "server_busy",
    "server_shutdown",
    "internal_error",
];
export const GAME_OVER_REASONS = [
    "wall",
    "snake_body",
    "head_to_head",
    "black_hole",
    "star_beast",
    "forfeit",
    "opponent_left",
    "desync",
    "timeout",
    "server_shutdown",
    "draw",
    "unknown",
];
export const PVP_LIMITS = {
    minTick: 0,
    maxTick: 2_147_483_647,
    minSeq: 1,
    maxSeq: 2_147_483_647,
    minRoomCodeLength: 4,
    maxRoomCodeLength: 8,
    minPlayerIdLength: 4,
    maxPlayerIdLength: 64,
    minSessionTokenLength: 8,
    maxSessionTokenLength: 128,
    maxNicknameLength: 20,
    maxClientVersionLength: 32,
    minStateHashLength: 8,
    maxStateHashLength: 128,
    maxBoardCoordinate: 255,
    minTickRate: 1,
    maxTickRate: 60,
    maxInputDelayTicks: 10,
    maxClockTime: Number.MAX_SAFE_INTEGER,
    maxQueuePosition: 250,
    maxOnlineCount: 250,
    maxQueuedCount: 250,
    maxWaitingMs: 86_400_000,
    maxCountdownMs: 10_000,
};
